"""add img col

Revision ID: 44f4c8696aac
Revises: 43928122e769
Create Date: 2025-11-27 12:55:10.080883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f4c8696aac'
down_revision: Union[str, Sequence[str], None] = '43928122e769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('img', sa.String(), server_default='https://picsum.photos/350/280', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'img')
    # ### end Alembic commands ###
